// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Jun 06 18:07:03 2018

16BitRegister 16BitRegister_inst
(
	.Reset(Reset_sig) ,	// input  Reset_sig
	.DBUS(DBUS_sig) ,	// input [15:0] DBUS_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.ENABLE(ENABLE_sig) ,	// input  ENABLE_sig
	.O(O_sig) 	// output [15:0] O_sig
);

